messages:
  friend:
    already-friends: "&6Friends &8\u00BB &cYou are already friends with &6%friend%"
    not-friends: "&6Friends &8\u00BB &cYou are not friends with &6%username%&c."
    not-allowing-requests: "&6Friends &8\u00BB &6%player% &cis not allowing friend requests."
    cannot-friend-self: "&6Friends &8\u00BB &cYou cannot send friend requests to yourself."
    no-request: "&6Friends &8\u00BB &cYou do not have a friend request from &6%username%&c."
    accept-requested: "&6Friends &8\u00BB &7You are now friends with &6%friend%&7."
    accept-requester: "&6Friends &8\u00BB &6%friend% &7accepted your friend request."
    add-requested: "&6Friends &8\u00BB &6%potential-friend% &7sent you a friend request. /f accept %potential-friend% to accept."
    add-requester: "&6Friends &8\u00BB &7You sent &6%potential-friend% &7a friend request."
    add-request-already-sent: "&6Friends &8\u00BB &cYou have already send a friend request to this player."
    add-request-already-received: "&6Friends &8\u00BB &6%potential-friend% &chas already sent you a friend request. Accept it with /f accept %potential-friend%&c."
    deny-requested: "&6Friends &8\u00BB &7You denied &6%not-friend%'s &7friend request."
    deny-requester: "&6Friends &8\u00BB &6%not-friend% &cdenied your friend request."
    help:
    - "&7-----------------[&6Friends Help&7]-----------------"
    - "&8/&6friend accept <player> &8- &7Accept a friend request."
    - "&8/&6friend add <player> &8- &7Send a friend request to a player."
    - "&8/&6friend deny <player> &8- &7Deny a friend request."
    - "&8/&6friend help &8- &7Displays this help message."
    - "&8/&6friend list &8- &7List your friends."
    - "&8/&6friend remove <player> &8- &7Unfriend a player."
    - "&8/&6friend toggle &8- &7Enable/disable friend requests."
    - "&7----------------------------------------------"
    list:
      size: 8
      header: "&7-----------------[&6Friends List&7]-----------------"
      no-friends: "&cYou do not have any friends. Add friends with /f add <player>"
      format: "&6%friend% &7is %status%&7."
      status:
        offline: "&coffline"
        unknown: "in an unknown realm"
        creative-0: "connected to &bCreative"
        factions-0: "connected to &cFactions"
        skyblock-0: "connected to &aSkyBlock"
        lobby-0: "in a lobby"
        lobby-1: "in a lobby"
        lobby-2: "in a lobby"
      footer: "&7---------------------------------------------"
    remove-remover: "&6Friends &8\u00BB &7You removed &6%old-friend% &7from your friends list."
    remove-friend: "&6Friends &8\u00BB &6%old-friend% &cremoved you from their friends list."
    requests:
      header: "&7--------------[&6Friends Requests&7]---------------"
      no-requests: "&cYou do not have any friend requests."
      format: "%potential-friend%"
      footer: "&7---------------------------------------------"
    toggle-enable: "&6Friends &8\u00BB &7You are now allowing friend requests."
    toggle-disable: "&6Friends &8\u00BB &cYou are no longer allowing friend requests."
    join: "&6Friends &8\u00BB &6%friend% &7joined."
    quit: "&6Friends &8\u00BB &6%friend% &7left."
  party:
    not-in-a-party: "&cYou are not in a party."
    accept-sender: "&6%invited% &7accepted your party invite."
    accept-receiver: "&7You accepted &6%inviter%'s &7party invite."
    deny-sender: "&6%invited% &cdenied your party invite."
    deny-receiver: "&7You denied &6%invitees% &7party invite."
    help:
    - "&7------------------[&6Party Help&7]------------------"
    - "&8/&6party accept <player> &8- &7Accept a party invite."
    - "&8/&6party deny <player> &8- &7Deny a party invite."
    - "&8/&6party help &8- &7Displays this help message."
    - "&8/&6party invite <player> &8- &7Invite a player to your party."
    - "&8/&6party kick <player> &8- &7Remove a player from your party."
    - "&8/&6party leave &8- &7Leave your party."
    - "&8/&6party list &8- &7List your party members."
    - "&8/&6party toggle &8- &7Enable/disable party invites."
    - "&7----------------------------------------------"
    invite-inviter: "&7You invited &6%invited% &7to your party."
    invite-invited: "&6%inviter% &7invited you to join their party. /p accept %inviter% to accept."
    kick-kicker: "&7You kicked &6%kicked% &7from your party."
    kick-kicked: "&7You have been removed from &6%kicker%'s &7party."
    leave-leaver: "&7You left &6%party-owner%'s &7party."
    leave-members: "&6%leaver% &7left your party."
    list:
    - "&7-----------------[&6Party List&7]------------------"
    - "&7Leader&8: &6%party-leader%"
    - ""
    - "&6%party-members%"
    - "&7---------------------------------------------"
    toggle-enable: "&7You are now allowing party requests."
    toggle-disable: "&cYou are no longer allowing party requests."
  private-message:
    format-sender: "&7To &6%receiver% &8\u00BB &7%message%"
    format-receiver: "&7From &6%sender% &8\u00BB &7%message%"
  player-not-found: "&cA player by the name of '&6%username%&c' was not found."
  invalid-arguments: "&cInvalid arguments! Try: &8/&6%command%&c."
  not-player: "&cThis command can only be executed by players."